Add log listener to suite starter
eiffel-community/etos-suite-starter pull request #20
Opened 2023-06-05 09:41 UTC by t-persson

### Applicable Issues

eiffel-community/etos#148
depends-on: eiffel-community/etos-suite-runner#38
depends-on: eiffel-community/etos-library#21

### Description of the Change

Add the ESR log listener to the YAML of ESR.

### Alternate Designs

None

### Benefits

Enables the collection of ETOS logs in the ESR.

### Possible Drawbacks

None

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Tobias Persson <tobias.persson@axis.com>

2023-06-05 09:59 UTC, t-persson commented
Failures are expected as we are dependent on an ETOS Library change. Won't merge until 3.1.0 of ETOS Library is released.

2023-06-07 07:27 UTC, fredjn submitted a review, later dismissed
Perhaps we should consider moving the k8s manifests (esr_yaml.py) into proper .yaml files.

2023-06-09 10:18 UTC, t-persson commented
> Perhaps we should consider moving the k8s manifests (esr_yaml.py) into proper .yaml files.

Possibly. Please write an issue. The "problem" with it is that we need to modify the values in a good way as well.
I guess it could be solved by using kustomize or another templating system for ESR.
Won't do anything in this PR at least :)

2023-06-15 08:35 UTC, fredjn requested changes

2023-06-15 08:35 UTC, fredjn commented on tests/test_suite_starter.py
>              f"Expected {self.suite_runner!r}, Was {image[0]!r}",
```suggestion
            f"Expected {self.suite_runner!r}, Was {image[1]!r}",
```

2023-06-15 08:38 UTC, fredjn approved these changes

2023-06-15 08:38 UTC, merged